dist: trusty
sudo: required
services:
- docker
language: go
go:
  - "1.13.x"
  
env:
  - GO111MODULE=on

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh

script:
- 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash make test; fi'
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash make testacc; fi'

branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
